services:
  # --- NGINX WEB SERVER ---
  nginx:
    image: nginx:alpine
    container_name: skeletron_nginx_nginx
    volumes:
      - ./www:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - web_network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skeletron_nginx_app.rule=Host(`skeletron-nginx.localhost`)"
      - "traefik.http.services.skeletron_nginx_app.loadbalancer.server.port=80"
      - "traefik.docker.network=web_network"

  # --- PHP-FPM ---
  php:
    build:
      context: .
    container_name: skeletron_nginx_php
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./www:/var/www/html/
    env_file:
      - .env
    networks:
      - default

  # --- DATABASE ---
  db:
    image: mariadb:latest
    container_name: skeletron_nginx_db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./skeletron_nginx.sql:/docker-entrypoint-initdb.d/skeletron_nginx.sql
    networks:
      - default

  # --- PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skeletron_nginx_pma
    environment:
      PMA_HOST: skeletron_nginx_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - web_network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skeletron_nginx_pma.rule=Host(`db.skeletron-nginx.localhost`)"
      - "traefik.http.services.skeletron_nginx_pma.loadbalancer.server.port=80"
      - "traefik.docker.network=web_network"

networks:
  web_network:
    external: true

volumes:
  db_data:
