services:
  # --- PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skeletron_nginx_pma
    environment:
      PMA_HOST: skeletron_nginx_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - web_network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skeletron_nginx_pma.rule=Host(`db.skeletron-nginx.localhost`)"
      - "traefik.http.services.skeletron_nginx_pma.loadbalancer.server.port=80"
      - "traefik.docker.network=web_network"

  # --- MOCK SMTP ---
  mailpit:
    image: axllent/mailpit
    container_name: skeletron_nginx_mailpit
    networks:
      - web_network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skeletron_nginx_mailpit.rule=Host(`mail.skeletron-nginx.localhost`)"
      - "traefik.http.services.skeletron_nginx_mailpit.loadbalancer.server.port=8025"
      - "traefik.docker.network=web_network"
